# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
