# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0004_season_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='id',
        ),
        migrations.AlterField(
            model_name='season',
            name='number',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
