# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='color',
            field=models.CharField(choices=[('green', 'verde'), ('orange', 'arancio'), ('red', 'rosso'), ('aqua', 'azzurro'), ('yellow', 'giallo')], default='azure', max_length=30),
            preserve_default=False,
        ),
    ]
