# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='abbreviation',
            field=models.CharField(max_length=1, unique=True),
        ),
    ]
