# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0002_auto_20160719_2123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='allocation',
            old_name='project',
            new_name='location',
        ),
    ]
