# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0003_auto_20160810_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='color',
            field=models.CharField(choices=[('green', 'verde'), ('orange', 'arancio'), ('red', 'rosso'), ('#3a87ad', 'azure')], default='azure', max_length=30),
        ),
    ]
