# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0004_auto_20160810_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='abbreviation',
        ),
    ]
