# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0005_remove_location_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='color',
            field=models.CharField(choices=[('green', 'verde'), ('orange', 'arancio'), ('red', 'rosso'), ('#3a87ad', 'azzurro'), ('hotpink', 'rosa')], default='azure', max_length=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='people',
            field=models.ManyToManyField(related_name='people', through='allocations.Allocation', to='people.Person'),
        ),
    ]
