# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 21:08
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0006_auto_20160813_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='comment',
            field=models.TextField(blank=True, verbose_name='commento'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='end_date',
            field=models.DateField(verbose_name='data fine'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocations.Location', verbose_name='luogo'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person', verbose_name='persona'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='start_date',
            field=models.DateField(verbose_name='data inizio'),
        ),
        migrations.AlterField(
            model_name='location',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=10),
        ),
    ]
