# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['surname'], 'verbose_name_plural': 'people'},
        ),
    ]
