# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='office',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
