# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20160719_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
