# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_person_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='rank',
            field=models.CharField(choices=[('1', 'stagista'), ('2', 'consultant'), ('3', 'senior'), ('4', 'assistant manager'), ('5', 'manager'), ('6', 'partner')], max_length=30),
        ),
    ]
