# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_remove_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
