# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_membership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
